before_script:
  - "psql -c 'create database socialite_test;' -U postgres >/dev/null"
  - "mysql -e 'create database socialite_test;' >/dev/null"
rvm: 
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - rbx-2.0
  - ree
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
